# Generated by Django 4.2.3 on 2023-07-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_song_album_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='playlist_song',
            field=models.ManyToManyField(blank=True, to='api.playlist'),
        ),
    ]
