# Generated by Django 4.2.3 on 2023-07-20 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_song_album_id_alter_user_liked_songs_song_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_liked_songs',
            name='song_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likedsongs', to='api.song'),
        ),
        migrations.AlterField(
            model_name='user_liked_songs',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeduser', to=settings.AUTH_USER_MODEL),
        ),
    ]
