# Generated by Django 4.2.3 on 2023-07-20 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_liked_songs_song_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='liked_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User_Liked_Songs',
        ),
    ]
