# Generated by Django 4.2.3 on 2023-07-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_artist_album_album_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ManyToManyField(related_name='albums', to='api.artist'),
        ),
    ]
