# Generated by Django 4.2.3 on 2023-07-21 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_album_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium', to=settings.AUTH_USER_MODEL),
        ),
    ]
