# Generated by Django 4.2.3 on 2023-07-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_premium_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
