# Generated by Django 4.2.3 on 2023-07-21 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_customuser_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='max_otp_try',
            field=models.CharField(default=3, max_length=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.CharField(default='UTC', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp_max_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.TextField(unique=True, validators=[django.core.validators.RegexValidator(message='Phone Number must be 10 digits', regex='^\\d{10}')]),
        ),
    ]
