# Generated by Django 4.2.3 on 2023-07-24 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_customuser_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.TextField(validators=[django.core.validators.RegexValidator(message='Password must be at least 8 characters long and include both letters and numbers.', regex='^(?=.*[a-zA-Z])(?=.*\\d).{8,}$')]),
        ),
    ]
