# Generated by Django 4.2.3 on 2023-07-25 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_customuser_otp_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Password must be at least 8 characters long and include letters and numbers and special characters', regex='^(?=.*[a-zA-Z])(?=.*\\d)(?=.*[@#$%^&+=]).{8,}$')]),
        ),
    ]
