# Generated by Django 4.2.3 on 2023-07-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.IntegerField(default=2134),
            preserve_default=False,
        ),
    ]
