# Generated by Django 4.2.3 on 2023-08-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_artist_artist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_image',
            field=models.ImageField(default=1, upload_to='profile'),
            preserve_default=False,
        ),
    ]
