# Generated by Django 4.2.3 on 2023-08-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_album_album_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='album_image',
            field=models.ImageField(default=1, upload_to='profile'),
            preserve_default=False,
        ),
    ]
