# Generated by Django 4.2.3 on 2023-08-07 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_playlist_album_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='album_image',
            new_name='playlist_image',
        ),
    ]
