"""
Django settings for companyapi project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/
CSRF_TRUSTED_ORIGINS = [ "http://localhost:8000","http://localhost:4200","http://localhost:4200/"]

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-aix*7hl1gxpzjr1v8&bd(atuxsj5d#@$tdi(egxgw%-&qjyzcx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

#Custom User 
AUTH_USER_MODEL  = 'api.CustomUser'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
        'rest_framework',
        'api',
        'rest_framework.authtoken',
            'corsheaders'


]
CORS_ORIGIN_ALLOW_ALL=True
MIDDLEWARE = [
        'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'companyapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'companyapi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
   'default': {
       'ENGINE': 'django.db.backends.postgresql_psycopg2',
       'NAME':'postgres',
       'USER': 'postgres',
       'PASSWORD': 'mysecretpassword',
       'HOST': 'localhost',
       'PORT':'5432'
   }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
     
}

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MAX_OTP_TRY=3
MIN_PASSWORD_LENGTH=10
SMS_API_KEY = "49a97fa3-27fb-11ee-addf-0200cd936042"

STATIC_URL = 'static/'
import os
STATIC_ROOT = os.path.join(BASE_DIR,'static')

# Media Settings

MEDIA_URL = ''

MEDIA_ROOT = ''
print(BASE_DIR)
# settings.py

CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",
    "http://localhost:4200",
    "http://localhost:8000",  
    "http://127.0.0.1:8000", 
]
CSRF_TRUSTED_ORIGINS = [ "http://localhost:4200/",
                        "http://localhost:4200/"
    "http://localhost:8000",  
    "http://127.0.0.1:8000"]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
CORS_ORIGIN_WHITELIST = [
    'http://localhost:8000',
    "http://localhost:4200",
    "http://localhost:4200/"
]
# settings.py
CSRF_COOKIE_SECURE = True
# CSRF_COOKIE_DOMAIN = 'http://localhost:4200'
# CSRF_COOKIE_PATH = '/'
# # Example of additional CORS settings
# CORS_ALLOW_HEADERS = ['Authorization', 'Content-Type']
# CORS_ALLOW_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']

